### ISSUE TITLE
Missing '/' in images urls

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-responsive-images-plugin#103]
I've noticed a strange behavior.  
The images are correctly generated, but not in the right place. 

In [ReponsiveImage@getStoragePath](https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/5cc4238e6072e5e68e7871b84fe67cab07a9b9ea/classes/ResponsiveImage.php#L226-L238) method : 
https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/5cc4238e6072e5e68e7871b84fe67cab07a9b9ea/classes/ResponsiveImage.php#L228

`$this->getPartitionDirectory()` give a string like `be1/c5a/0a5/`,   
but `temp_path` function return a string without the leading slash `...\storage\temp\public\be1\c5a\0a5`  

Then the resulting path is combine with the file name :
https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/5cc4238e6072e5e68e7871b84fe67cab07a9b9ea/classes/ResponsiveImage.php#L233  

giving in that case : 
`...\storage\temp\public\be1\c5a\0a5633322c8238dc695117336__400.jpg`  (two folders depth in public temp)

I think the result should be  :
`...\storage\temp\public\be1\c5a\0a5`**`\`**`633322c8238dc695117336__400.jpg`  (three folders depth in public temp)

Is there an error in my installation or are any of you experiencing this issue?

**Comment by tobias-kuendig** [comment]
I cannot reproduce the issue with `temp_path`. If the input string contains a trailing slash, the output of `temp_path` does as well.

What does this return in a tinker session on your host?

```php
temp_path('example/')

=> "/app/storage/temp/example/"
```

**Comment by damsfx** [comment]
@tobias-kuendig 
```bash
$ php artisan tinker
> temp_path('example/')
```
 - On a linux webserver :  `"/home/mywebsite/public_html/storage/temp/example"`
 - On a Windows webserver : `"P:\_Sites\mywebsite\storage\temp\example"`
 
 Using `temp_path('example')` give me the same result.

**Comment by tobias-kuendig** [comment]
That is very strange! This must be a difference in how Laravel returns the path.

But your concern is valid. On your setup, the path is generated wrong because the trailing slash is missing.

If someone wants to provide a PR that normalizes the trailing slashes on the temp_path return value I will merge it quickly.
