### ISSUE TITLE
Could not process image - JPG

### ISSUE THREAD

**Issue by RoccellaRocks** [OFFLINE-GmbH/oc-responsive-images-plugin#11]
Hello,
I have a normal and common JPG image in my home page and I would like it to be processed by the plugin. I have also tested this with another JPG and a PNG. I have also performed a test inside and outside of a partial, but nothing changed.

Inside the log I find this error:
`[2016-11-13 15:01:25] production.WARNING: [OFFLINE.ResponsiveImages] Could not process image storage/app/media/my-image.jpg {"exception":"[object] (ErrorException(code: 0): imagesx(): 552 is not a valid Image resource at /var/www/public/vendor/october/rain/src/Database/Attach/Resizer.php:213)"} `

How can I understand what is the **source of this issue**?
Is there any place where I can get any other hints about the origin of the problem?

Thanks for your support.

**Comment by tobias-kuendig** [comment]
A different jpg/png works? Is this only with this one image?

Could it be that your image is corrupted? Are you on linux or mac? What is the output of

```
file yourimage.jpg 
```

You can look at `Resizer.php` line 213 and see what exactly is passed to the `imagesx` function call. Either it is not a file that is passed in or it is corrupted.

**Comment by RoccellaRocks** [comment]
**I have already tested it with different images.**
I am on Mac OS X 10.11.6, using Vagrant with Scotch Box.

The output of that command is:
`my-image.jpg: JPEG image data, EXIF standard`

I am trying to generate **19 different breakpoints** for my images (and I would need twice of them).
I reduced the number of breakpoints and it just works.

I think the issue is related to the **large amount of breakpoints** required; however I will have to find another solution because I need all these breakpoints.

**Comment by tobias-kuendig** [comment]
Could it be that you run out of RAM? Have you tried increasing the memory
limit in your php.ini? I'll try to reproduce the problem tomorrow.

Giuseppe Roccella <notifications@github.com> schrieb am So., 13. Nov. 2016,
17:56:

**Comment by RoccellaRocks** [comment]
Increasing the RAM limit solved my issue. I am wondering what would happen when it loads a page full of images with 19*2 breakpoints...

Thanks for your help.

**Comment by abhi1693** [comment]
I'm having the same issue and increasing the RAM (increased to 1024M) didn't solve it for me. I'm using Ubuntu 16.04 with apache2 and php 7.0. None of my images are corrupt and all have jpg extension.

**Comment by tobias-kuendig** [comment]
How many images/breakpoints are you processing?

Abhimanyu Saharan <notifications@github.com> schrieb am Mi., 11. Jan. 2017,
18:54:

**Comment by abhi1693** [comment]
I'm processing on an average of 5 images per page with 6 breakpoints.

**Comment by tobias-kuendig** [comment]
Looks like there is a memory leak while generating the images. 5x6 images shouldn't be a problem, but it's hard to say how much RAM exactly the conversion needs. Could you by any change do some profiling and figure out where exactly the memory gets eaten up?

I'll have to look at this.

**Comment by abhi1693** [comment]
This is the snapshot from my profiler. I don't know how to spot a memory leak using this data as I have never done it before. Let me know if you need any more data from my side.


[Heap-20170112T162230.heapsnapshot.zip](https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/files/701440/Heap-20170112T162230.heapsnapshot.zip)

**Comment by abhi1693** [comment]
I solved my problem of responsive images by wrapping the Rainlab blog post component inside a `div` and then used `JQuery` to inject `img-responsive` class to the `img` tags. And it worked since I was using `Bootstrap`. But I preferred your plugin but could not get it to work properly according to my needs.

**Comment by tobias-kuendig** [comment]
Closed due to inactivity.
