### ISSUE TITLE
{{ svg(path) }} don't work with parent theme

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-responsive-images-plugin#110]
Hello,

I have a parent and a child theme.

My images assets are in my parent theme, cause shared between several child theme.

In my child theme, when I do this 

    svg('assets/img/myimage.svg')

The logic would suppose it would search the `assets/img/myimage.svg` in my current child theme, if it does not exists, load my `assets/img/myimage.svg` in the parent theme.

Instead of that, my image is not displayed because not present in my child theme.

Best regards

**Comment by PubliAlex** [comment]
Bump, I could reproduce the bug on 2 different sites using parent theme feature. Can somebody else reproduce ?

**Comment by tobias-kuendig** [comment]
I guess this does not return the correct theme folder?

https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/f962f0391b318ba396c102503b4f70e958340392/Plugin.php#L143C1-L143C61

**Comment by PubliAlex** [comment]
@tobias-kuendig The active theme's code is the right one, but it lacks a backup solution that fetches the file from the parent theme when it doesn't exist in the active theme.

I imagine there's a native October function for this, given that it's the CMS default behavior for pages, partials, content etc., but I haven't found it.

**Comment by tobias-kuendig** [comment]
I see, give v2.6.2 a try, it should be fixed there.

Thank you for the report @PubliAlex  and @Zmove
