### ISSUE TITLE
Refactored FocusPoint is bugged

### ISSUE THREAD

**Issue by zbigniew-glazer** [OFFLINE-GmbH/oc-responsive-images-plugin#113]
October CMS crashes with the following error when using this type of tag in my layout:

{variable type="section" label="Lista" tab="Pricelist"}{/variable}
{repeater name="section" groups="themes/deo/meta/pricelist.yaml" tab="Price List" prompt="Add item"}
{# parser fail if there is noting between open and close tag #}
{/repeater}

Can't edit the page and getting this kind of error:
"OFFLINE\ResponsiveImages\Classes\Focuspoint\FocuspointExtension::OFFLINE\ResponsiveImages\Classes\Focuspoint\{closure}(): Argument #1 ($path) must be of type string, null given, called in /home/admin/domains/demo/public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 421" on line 21 of /home/admin/domains/demo/public_html/plugins/offline/responsiveimages/classes/focuspoint/FocuspointExtension.php

![error](https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/assets/73530167/7492c797-c3b1-40ae-a8c9-3c14bbbbe49f)
I had to roll back to 2.6.3

**Comment by tobias-kuendig** [comment]
Thank you for the report! This is fixed in v2.7.3.

**Comment by zbigniew-glazer** [comment]
Wow. You are quick! Thanks
