### ISSUE TITLE
Does Not work at all

### ISSUE THREAD

**Issue by worldofsmarty** [OFFLINE-GmbH/oc-responsive-images-plugin#12]
It always logs entry into an error log as [OFFLINE.ResponsiveImages] Image projects/scopehosts/storage/app/media/tt14.jpg does not exist

But the link does exist and its showing image file. I dont know weather i am making any mistakes. Kindly let me know what may be the reason.

Thank you.

**Comment by tobias-kuendig** [comment]
Do you have any redirects via .htaccess or another server config in place?

Can you point me to an online example of your website?

**Comment by worldofsmarty** [comment]
http://tecobytes.com/projects/scopehosts/

**Comment by worldofsmarty** [comment]
Can you come on Slack so that i can pm you the logins as well if required

**Comment by tobias-kuendig** [comment]
This issue was resolved by pm.
