### ISSUE TITLE
Use different html parser

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-responsive-images-plugin#13]
The use of the \DOMDocument class can break some html (see https://github.com/responsiv/uploader-plugin/issues/17) since it removes invalid markup.

**Comment by Alex360hd** [comment]
Is \DOMDocument configurable ? So you could specify that scripts tags are not considered as invalid markup ?

**Comment by tobias-kuendig** [comment]
I do not think this is possible but if someone has more insights in this problem I'm glad for any inputs.

The whole DOM API in PHP seems very risky to use to me. It effectively parses the DOM tree and generates a complete new document after processing the HTML. I'm looking for something that touches the original HTML only minimally and keeps everything that doesn't need changes untouched.

**Comment by Alex360hd** [comment]
Hello,

Any update about that ? Because I disabled the module by waiting a solution with file upload compatibility. But now google officially announced that the mobile index will have priority over the desktop one, so I would like to be able to optimize my pages by serving responsive images.

**Comment by tobias-kuendig** [comment]
No, I haven't come around any better DOM parser for PHP than \DOMDocument.

What you can do is to override the [`file-multi.htm`](https://github.com/responsiv/uploader-plugin/blob/master/components/fileuploader/file-multi.htm#L49) partial in your theme and replace the `script` template with an invisible `div`. That should make it work.

```html
<!-- themes/your-theme/partials/fileUploader/file-multi.htm -->

<!-- Template for new files (use a div instead of script) -->
<div style="display: none;" id="uploaderTemplate{{ __SELF__ }}">
    <div class="upload-object dz-preview dz-file-preview">
        <div class="icon-container">
            <img data-dz-thumbnail src="{{ 'plugins/responsiv/uploader/assets/images/upload.png'|app }}" />
        </div>
        <div class="info">
            <h4 class="filename">
                <span data-dz-name></span>
            </h4>
            <p class="size" data-dz-size></p>
            <p class="error"><span data-dz-errormessage></span></p>
        </div>
        <div class="meta">
            <a
                href="javascript:;"
                class="upload-remove-button"
                data-request="{{ __SELF__ ~ '::onRemoveAttachment' }}"
                data-request-confirm="Are you sure?"
                >&times;</a>
            <div class="progress-bar"><span class="upload-progress" data-dz-uploadprogress></span></div>
        </div>
    </div>
</div>
```

**Comment by Alex360hd** [comment]
Thank you for the answer. I will test that !

**Comment by damsfx** [comment]
Hi,  

In my project I use a plugin who provide script based templates.  
**ALL closing tags are removed !!**

Reproduce the issue :   
1 - insert in your layout : 
````
<script>
test = {
    "elements":{
         foo: '<span class="cc-header">foo</span> ',
         bar: '<span id="cookieconsent:desc" class="cc-message">bar</span>',
    }
};
</script>
````
2 - You'll get : 
````
<script>
test = {
    "elements":{
         foo: '<span class="cc-header">foo ',
         bar: '<span id="cookieconsent:desc" class="cc-message">bar',
    }
};
</script>
````
It's really a blocking factor to use this plugin.  
Regards

**Comment by kiselli** [comment]
I found one, that looks promising: https://github.com/thesoftwarefanatics/php-html-parser

The last option would be string replace with regex.

**Comment by kiselli** [comment]
> I found one, that looks promising: https://github.com/thesoftwarefanatics/php-html-parser
> 
> The last option would be string replace with regex.

Does not work very well. We loose <script> Tags in content.

Here is my work: https://github.com/kiselli/oc-responsive-images-plugin/tree/change-dom-parser

I think we have to work with regex expressions. Which of course will boost up the performance 😉

**Comment by tobias-kuendig** [comment]
> I think we have to work with regex expressions. 

This sounds risky, but let's see how it works out. While tinkering around with the idea I came up with the following regex:

```regex
/<img[\s\S]*?(?:src)=(?:"|')(?<src>[^"']+)(?:"|')[\s\S]*?>/mis

**Comment by obuchmann** [comment]
We can use the Regex to catch whole image tag and maybe run a Dom Manipulation on this image tag only? Should work with http://php.net/manual/de/function.preg-replace-callback.php

**Comment by tobias-kuendig** [comment]
:tada: `v2.0.0` is ready for testing as edge update! :fire:

https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/commit/2b67b82a26a4fc6f1bcdc098ecdd1539d2bf8184

**Comment by Eoler** [comment]
Is this solved in released plugin version?

**Comment by tobias-kuendig** [comment]
Yes! It has been for almost a year now. Thanks for pointing this out. We switched to a regex based approach.
