### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Ladylain** [OFFLINE-GmbH/oc-responsive-images-plugin#20]
Hi , 

I was haapy when i found your plugin cause it was written that it could do what i wanted to do :) 

But unfortunately, since i have installed it, it doesn't make `srcset` into my render, even if those are called like this : 
`<img src="/themes/..../image.jpg" />`
or 
`<img src="{{ "image.jpg"|media }}"/>`

do you know how to resolve this ? 

thanks

**Comment by tobias-kuendig** [comment]
Do you have your `app.url` config entry set up correctly?

See https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/issues/16#issuecomment-402647394

**Comment by Ladylain** [comment]
Hi and thanks for you answer, i've just read the other issue, and it doesn't seem to change anything. 

I am in local dev mode, with a local url like october.local and i've changed the url in app.php to http://october.local but it doesn't work, 

Do you have another solution maybe ? 

Fyi, my plugin is up to date.

**Comment by tobias-kuendig** [comment]
Have you enabled logging in the backend settings of the plugin? If so, do you find any logged errors in your `storage/logs/system.log`?

**Comment by Ladylain** [comment]
Yes it's enabled, i found this issue in system.log 
`[2018-08-13 14:49:49] development.WARNING: [OFFLINE.ResponsiveImages] Could not process image http://october.local/storage/app/uploads/public/5b2/8f2/d08/5b28f2d0885ca765982850.jpg {"exception":"[object] (ErrorException(code: 0): imagesx(): supplied resource is not a valid Image resource at C:\\Users\\******\\Documents\\october\\vendor\\october\
ain\\src\\Database\\Attach\\Resizer.php:210)`

Could it be possible that there is a conflict with Resizer ?

**Comment by Ladylain** [comment]
this file is correct and after verification, it's working with your plugin 
When i look at the code for this file, it is called like this : 
```src="{{ record.header_image.thumb(1198,544,'crop') }}"```
while files which don't work with the plugin are called like 
```src="myimage.jpg" ```

there is several image in the log file but no images are from `src="myimage.jpg" `

**Comment by tobias-kuendig** [comment]
Closed due to inactivity.
