### ISSUE TITLE
Incompatible with multisite

### ISSUE THREAD

**Issue by anschinsan** [OFFLINE-GmbH/oc-responsive-images-plugin#21]
Hi tobias-kuendig,

first of all thank you for your work with this plugin! I'm using it on several October CMS sites, one oft them manages several landing pages with different subdomains. To present on each subdomain a different theme, I use the Multisite plugin (https://octobercms.com/plugin/voipdeploy-multisite).

Now with this setup your plugin unfortunately does not work because only one of the subdomains can be set in the configuration.

I took a look into your code and got the plugin working by changing two lines a little bit - but I think I did not really change the logic of the plugin. As I've seen, this is an issue as well for other users ...  so now I wonder, if it would be possible to alter the plugin so that others don't run into this problem (and I can safely update the plugin in the future. :)

Unfortunately I do not have any experience with Pull requests ... but I hope, you do take a look anyway.
This is my change:

in plugins/offline/responsiveimages/classes/ResponsiveImage.php

protected function normalizeImagePath($imagePath) 
   {
        $base = $this->getBase();

        // If a relative path gets processed make sure to remove
        // any subdirectory from the URL.
        if(substr($imagePath, 0, 4) !== 'http') {            
            $subdir = trim(str_replace($base, '', env('APP_URL')), '/') . '/';
            return base_path(str_replace($subdir, '', $imagePath));
        } else {
            //$imagePath = trim(str_replace(config('app.url'), '', $imagePath), '/');
            $imagePath = trim(str_replace($base, '', $imagePath), '/');
            return base_path($imagePath);
        }
    }

In any case I would appreciate your feedback!

Thank you in advance
anschinsan

**Comment by tobias-kuendig** [comment]
Hi @anschinsan 

Thank you for your suggestion, this sounds interessting!

Could you test your setup with the following version of the ResponsiveImage class file?
https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/d5dec501e5ad4d8cd8b0c9fc7b8fc866699c80c9/classes/ResponsiveImage.php

If everything is working as expected I'll release a new version.

**Comment by anschinsan** [comment]
Hi @tobias-kuendig,

Thank you so much for your fast response and for implementing this! I've tested it on 2 sites and it works perfect.

anschinsan

**Comment by tobias-kuendig** [comment]
Thank you for testing! I just released a new versoin 1.1.8 to the marketplace that includes this fix.
