### ISSUE TITLE
[solved] Could not process image

### ISSUE THREAD

**Issue by Lajmenko** [OFFLINE-GmbH/oc-responsive-images-plugin#22]
Hello, I started using the plugin, yet noticed that it doesn't work as intended, and I get error messages like: 
[OFFLINE.ResponsiveImages] Could not process image storage/app/media/featured/projects/Ang/Halloween.png

I tried to browse previous issues, yet if I understood correctly- they regarded to previous plugin versions

**Comment by Lajmenko** [comment]
Update: 

Issue was caused by plugin not targetting custom posts from blog plugin. Fixed this issue by editing entries in database by adding manually (class="img-responsive") to troublesome elements.

**Comment by tobias-kuendig** [comment]
> Could not process image storage/app/media/featured/projects/Ang/Halloween.png

How big is this image (in terms of size and dimensions)?

> Issue was caused by plugin not targetting custom posts from blog plugin.

Does your app.url config entry match your server's hostname?

**Comment by tobias-kuendig** [comment]
Closed due to inactivity.
