### ISSUE TITLE
breaks use of html_email() and html_mailto()

### ISSUE THREAD

**Issue by cemik** [OFFLINE-GmbH/oc-responsive-images-plugin#24]
Breaks obfuscate function of html_email() and html_mailto():
{{ html_mailto('test@test.com')|raw }}
`<a href="&#x6d;&#97;i&#108;to:t&#101;&#x73;&#x74;&#64;t&#x65;s&#116;&#x2e;&#99;o&#109;">t&#101;&#x73;&#x74;&#64;t&#x65;s&#116;&#x2e;&#99;o&#109;</a>`

When plugin is enabled the output is:
`<a href="mailto:test@test.com">test@test.com</a>`

**Comment by tobias-kuendig** [comment]
Thank you for the heads up. This won't be possible to fix since we have to parse and rewrite the DOM to add the srcset attributes. This will turn the html entities back into normal characters.
