### ISSUE TITLE
Generate all resized images via console command

### ISSUE THREAD

**Issue by obuchmann** [OFFLINE-GmbH/oc-responsive-images-plugin#25]
It would be nice to provide a shell command to generate all resized images via a console command.

**Comment by tobias-kuendig** [comment]
This won't be possible unless the pages are pre-compiled and cached before hand.

We need the effective URLs to resize the images. The original `| media` and `getThumb()` calls cannot be used for this plugin to work properly.

We could use the compiled views in the storage directory but this will never get all images if not all pages have been called before.

**Comment by kiselli** [comment]
Whats about a list of pages to precompile and parse for media items?

RainLab.Pages does something simmilar to determine all possible urls for the StaticMenu. 

We could use the pages.menuitem.resolveItem Event if provided to determine most of the pages to render. Check out the RainLab.Sitemap plugin, they do something simmilar to offer all possible Urls to the User. Custom Types can be registered very easy. See RainLab.Blog for implementation details of custom types.

> Registering new sitemap definition item types
> The Sitemap plugin shares the same events for registering item types as the Pages plugin. See the documentation provided by this plugin for more information.
>
> A small addition is required when resolving items, via the following event:
>
> pages.menuitem.resolveItem event handler "resolves" a menu item information and returns the actual item URL, title, an indicator whether the item is currently active, and subitems, if any.

cite: https://octobercms.com/plugin/rainlab-sitemap#documentation

I'm not sure if its a good idea to implement this in another plugin, the compile effort would only take affect on a custom invoke of the console command

**Comment by tobias-kuendig** [comment]
What's your usecase? If you want to pre-resize them images maybe the easiest solution is to let a link checker crawl your site. This would trigger the resize for every image.

**Comment by kiselli** [comment]
Yes, thats our current approach. 

The usecase is a deployment via a script (updating some plugins and themes) and a cache clear afterwards. The processing of the images may start afterwards via a console command. It might be more efficent to use an internal logic than a crawler.

**Comment by tobias-kuendig** [comment]
I like the idea, but the implementation won't be easy. I'm leaving this issue open in case someone is willing to implement this. I unfortunately don't have the resources to do this myself.

**Comment by tobias-kuendig** [comment]
This was fixed in #26
