### ISSUE TITLE
Version 2.0.2 loads all images in combination with lazysizes

### ISSUE THREAD

**Issue by Verbat** [OFFLINE-GmbH/oc-responsive-images-plugin#29]
I'm using the layzyloader lazysizes (https://github.com/aFarkas/lazysizes) and after an update to the latest version of responsive images into 2.0.2 all images are downloaded on page load.

I really don't have an explanation why it behaves this way as the generated img code looks the same to me as before. I'm wondering if the update is interfering somehow because when I'm switching back to responsive images 2.0 it works as intended and only preloads the images in the viewport.

I tried it several times including deleting the cache but only in v2.0 it works.

This is how my img tag looks like in my partial  
`  <img src="{{ 'assets/images/black.jpg'|theme }}" data-sizes="auto" data-src="{{ datasheet.image | media  }}" alt="{{ datasheet.title }}"
          sizes="(max-width: 768px) 640px,
                  100vw">`

This are my settings in your Plugin:

Images sizes 
320,640,960

src-Attribut 
data-src

srcset-Attribut 
data-srcset

class-Attribut
lazyload

Any idea what causes this?

**Comment by Verbat** [comment]
Yep, that's causing that all images are loaded. If i comment the above line out it works as intended.

**Comment by tobias-kuendig** [comment]
Thank you! This is fixed in version 2.0.3.
