### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-responsive-images-plugin#31]
Hello,

Very small request here, but it would be great to update the doc to inform about the `php artisan responsive-images:generate` command, svg support etc....

When I talk about the doc, I mean the one on october cms side, that you can access when you go to settings > updates, without leaving your website backend.

Thank you

**Comment by tobias-kuendig** [comment]
I've added the Pre-generate images section to the marketplace description. The svg support was already documented.

Thank you for the feedback!
