### ISSUE TITLE
|media and |theme support for svg function

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-responsive-images-plugin#32]
Hello,

Would it be possible to add support to |media and |theme when you work with SVG ? To keep the same october core syntax, like all other assets.

Thank you

Alex

**Comment by tobias-kuendig** [comment]
`svg('yourfile.svg' | theme )` doesn't work?

**Comment by PubliAlex** [comment]
No, it display a fatal error : 

>The stream or file "/storage/logs/system.log" could not be opened: failed to open stream: Permission denied
/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php line 107

Just removing |theme works as, by default, it looks in the theme directory, but I would prefer to stay with the october CMS syntax as I'm used to use it

**Comment by tobias-kuendig** [comment]
> The stream or file "/storage/logs/system.log" could not be opened: failed to open stream

This is a permission problem on your storage folder. Make sure to fix that!

In v2.0.7 the |theme and |media URLs are now handled correctly. Please close this issue once you had time to test this :+1: 

Thanks for the feedback!

**Comment by PubliAlex** [comment]
Worked perfectly, thank you very much !
