### ISSUE TITLE
strange issue with SVG 

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-responsive-images-plugin#33]
Hello,

I'm encountering weird issue with SVG, I use svg() function to embed some SVG inline (very useful !). Works perfecly on our development server, it does not work on our production server.

Instead of the SVG, it display a square with a red cross in it, with the following error when you look at the HTML code : 

> [OFFLINE.ResponsiveImages] Inline SVG 'https://www.website.com/themes/mytheme/assets/img/maintenance/dots1.svg' not found!

If I open 'https://www.website.com/themes/mytheme/assets/img/maintenance/dots1.svg' on a new tab, I can see the SVG, so it's not related to a wrong path.

I don't have any errors in server or console log, I wonder if that feature depend on a php / apache extension, or something that could be enabled on our dev server and not on the prod one.

Thank you for your help

Alex

**Comment by PubliAlex** [comment]
If I look at the event log, I get the following error : 

[OFFLINE.ResponsiveImages] Cannot inline svg https://www.website.com/themes/lusso/assets/img/maintenance/angle2.svg. Not found in /var/www/vhosts/website.com/httpdocs/themes/mytheme/https://www.website.com/themes/website/assets/img/maintenance/angle2.svg.

As you can see, he try to add the full website URL after the /mytheme folder...

If I disable |theme after my SVG call, it works. It's very strange because it works on the other server (with the |theme declaration)

Do you have an idea about the thing that could explain that difference ? (php version ? configuration ?)

**Comment by tobias-kuendig** [comment]
Could it be that your `app.url` config is not matching the effetive host name?

You can try to debug the link generation here:
https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/develop/classes/svg/SVGInliner.php#L38

**Comment by PubliAlex** [comment]
You are right, I'm a dump :/
