### ISSUE TITLE
code reuse

### ISSUE THREAD

**Issue by webeks** [OFFLINE-GmbH/oc-responsive-images-plugin#4]
Hi

Im trying to prepare a plugin that would offer image manipulation for OctoberCMS.

It should be capable of:
- watermarking
- image resize (max width)
- responsive image
- image captions
- rewriting image path so that media dir can be protected and not publicly accessible 

May I include the code of your extension inside?

Thanks,
Miha

**Comment by tobias-kuendig** [comment]
Sounds great! Feel free to use everything you need.
