### ISSUE TITLE
Custom atttribute 

### ISSUE THREAD

**Issue by m49n** [OFFLINE-GmbH/oc-responsive-images-plugin#42]
I wanted to suggest adding another field to the settings, a custom attribute, for example, in the uikit3 framework, the uk-img attribute is used to enable the lazyload component (https://getuikit.com/docs/image).

And one question:
When i chenge "src" attribute in settings, on the site nothing happend

 Thanks.

**Comment by tobias-kuendig** [comment]
Can you provide some example markup (before/after)?

**Comment by m49n** [comment]
before: <img src="images/light.jpg" width="1800" height="1200" alt="" >
after: <img data-src="images/light.jpg" width="1800" height="1200" alt="" uk-img>

uk-img - it's a custom attribute 
data-src it's a fomer src

**Comment by tobias-kuendig** [comment]
The `src` option means that this:

```
<img data-src="test.jpg">
```

becomes 

```
<img src="test-resized.jpg">
```

not the other way around.

This plugin's job is to resize your images. If you need any special custom markup you'll have to generate it yourself. 

You can use the `class` option to select resized elements. I'm not familiar with UI kit but I'm sure you have the option to initialize the lazy loading on any kind of custom NodeList (`document.querySelectorAll('.responsive-image')`).

For the time being I do not have the resources to implement such a custom attribute feature. If you (or someone else) provides a PR for it I can integrate it.
