### ISSUE TITLE
After new update the plugin not working

### ISSUE THREAD

**Issue by pam2kas** [OFFLINE-GmbH/oc-responsive-images-plugin#43]
After update the new realease with focus point the plugin not generated the image and there is no error log show.

**Comment by tobias-kuendig** [comment]
Thank you  @pam2kas, for this report. 

This problem was fixed in 997d4cfd3f81032a92e3d7616741ba1b8b88670b, but due to a bug on the October Marketplace I won't be able to release the new version by tomorrow. You can, however, patch your installation manually for the time being.

**Comment by tobias-kuendig** [comment]
The fix has been release as v2.1.3. Thanks again for your report @pam2kas!
