### ISSUE TITLE
Feature: Multiple attribute scan support?

### ISSUE THREAD

**Issue by mauserrifle** [OFFLINE-GmbH/oc-responsive-images-plugin#47]
As far as I understand currently it's only possible to change the `src` attributes (for lazy loading and such). But in some projects there are normal images (`src`) and some lazy loading (`data-src`). It would be cool to add multiple (comma separated). So it works for all images on the pages.

**Comment by tobias-kuendig** [comment]
Definitely! Good point. In theory, as the provided attribute name is inserted in  [the image matching regex](https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/develop/classes/DomManipulator.php#L33), you could try and specify a regex pattern and see if this already works: `src|data-src`

**Comment by PubliAlex** [comment]
+1 here, another real workd example. The excellent plugin [lazysizes](https://github.com/aFarkas/lazysizes), that use data-src for image tag, and data-bg for background images.

**Comment by tobias-kuendig** [comment]
This feature is now available in version 2.3.0. Simply define multiple src and srcset attributes (comma-separated):

| option | value |
| ----- | ----- |
| source | `src, data-src` |
| target | `srcset, data-srcset` |

Please let me know if you find any issues with this addition.
