### ISSUE TITLE
Provide settings in backend instead of overriding config.php

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-responsive-images-plugin#5]
Hello,

It would be great to define the different sizes of images directly in the october backend interface instead of config.php

Why ? Because october CMS can be multiwebsite with a plugin, or you can have different themes that need different breakpoints in one october installation, so it would make more sense to define that in the backend settings.

Alex

**Comment by tobias-kuendig** [comment]
This feature was implemented in version 1.1.0. Thanks for your input!
