### ISSUE TITLE
Bad TTFB when using this module

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-responsive-images-plugin#50]
Hello,

I have very bad TTFB as soon as I resize images using this module.

I created 2 sample files just containing 35 images each.

One with the following code : 

    <img src="{{ 'dummy.png'|media }}" />
    <img src="{{ 'dummy.png'|media }}" />
    etc.... (35 times)

The other with the following code : 

    <img src="{{ 'dummy.png'|media|resize(1000) }}" />
    <img src="{{ 'dummy.png'|media|resize(1000) }}" />
    etc.... (35 times)

When I compare TTFB, the first page is 182ms, the second page : 934ms.

The difference in TTFB seems quite heavy, and does not decrease even if reload the page several times. I could understand a high TTFB on the first page load, when all images needs to be resized, but don't understand for the next page load, when cached images should be served.

What do you think about this ?

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
I don't think the `|resize` filter is part of this plugin?

**Comment by PubliAlex** [comment]
ahh sorry, It wanted to post to abwebdevelopper/imagresizer plugin. Multiple tab issue
