### ISSUE TITLE
Apache Error

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-responsive-images-plugin#53]
After enabling the plugin, the `.htaccess` has been updated by the plugin and Apache return this errors in the log

```
[Tue Mar 17 08:42:58 2020] [alert] [client ::1] /Users/christophevidal/Sites/oc-accm/.htaccess: RewriteRule: unknown flag 'END', referer: http://oc-accm.local/backend/system/settings/update/offline/responsiveimages/config
[Tue Mar 17 08:43:01 2020] [alert] [client ::1] /Users/christophevidal/Sites/oc-accm/.htaccess: RewriteRule: unknown flag 'END', referer: http://oc-accm.local/backend/system/settings/update/offline/responsiveimages/config
[Tue Mar 17 08:43:08 2020] [alert] [client ::1] /Users/christophevidal/Sites/oc-accm/.htaccess: RewriteRule: unknown flag 'END', referer: http://oc-accm.local/backend/system/updates/install
[Tue Mar 17 08:43:08 2020] [alert] [client ::1] /Users/christophevidal/Sites/oc-accm/.htaccess: RewriteRule: unknown flag 'END', referer: http://oc-accm.local/backend/system/settings/update/offline/responsiveimages/config
[Tue Mar 17 08:43:08 2020] [alert] [client ::1] /Users/christophevidal/Sites/oc-accm/.htaccess: RewriteRule: unknown flag 'END'
```

it seems that this rule is not ok with my Apache
`    RewriteRule ^/?(.*)$ $1.webp [NC,T=image/webp,END]`

or this one

`RewriteRule ^/?(.*)$ %{DOCUMENT_ROOT}/plugins/offline/responsiveimages/webp.php?path=$1 [NC,END]`

I am using MAMP PRO 5.5

**Comment by tobias-kuendig** [comment]
What version of Apache are you running? It looks like the END flag was added in Apache 2.3.

**Comment by chrisvidal** [comment]
you are right,
I am using MAMP PRO 5.5 and It is still using Apache 2.2.x apparently,

**Comment by tobias-kuendig** [comment]
I'm closing this issue as providing the correct redirect rules (especially for older Apache versions) is out of the scope of this plugin.
