### ISSUE TITLE
way to handle @2x images

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-responsive-images-plugin#54]
Hello,

I use this plugin on a very regular basis and my graphist noticed me that images appears as blurry on high density screens like retina display.

I think it would be a nice addition to add support to that kind of screens in the module

What do you think about it ?

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
This plugin makes use of width (`w`) descriptors in the `srcset` attribute. This makes sure that for certain display sizes a fitting image variant is loaded.

Unfortunately, you cannot use both width descriptors (`w`) and density descriptors (`x`) in the a `srcset` attribute:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-srcset

If your image is `900px` wide, having a `1800w` size generated should equal to a `@2x` source. You can define what images the plugin should generate via the backend settings (`Generated image sizes`).

Adding an additional sizes might already be sufficient to solve this problem.

Alternatively, you can always specify your own custom `srcset` attribute using `@2x` sources. The plugin will leave img tags with an existing `srcset` attirubte untouched.

**Comment by PubliAlex** [comment]
Hello,

Thank you for the answer. So it means that if I need to display a image with a width of 1024 on a regular screen, I just have to provide a 2048 image size and define a 2048 size in Generated image size, and it should do the job ?

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
Exactly, as for as I understand the default browser behaviour that should give you the same results.

**Comment by PubliAlex** [comment]
Ok thank you
