### ISSUE TITLE
Bug when website is in a subfolder

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-responsive-images-plugin#65]
Hello,

I had a working website on a development server. I moved it to the production server, in a subfolder (so the same website that worked)

The inline SVG path doesn't work anymore, here is the error log I have :

[OFFLINE.ResponsiveImages] Cannot inline svg http://mywebsite.com/new/themes/moncigale/assets/img/linkedin.svg. Not found in /vhosts/mywebsite.com/httpdocs/new/themes/mytheme/http://mywebsite.com/new/themes/mytheme/assets/img/linkedin.svg.

As you can notice, the website url is repeated in the middle of the svg path, that's really weird

**Comment by tobias-kuendig** [comment]
Is your `app.url` config set up correctly?

https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/develop/classes/svg/SVGInliner.php#L38

**Comment by Zmove** [comment]
No you are right, I believed I tried all combination, but, by starting again (fresh, in the morning), it worked with the subfolder included in the app.url name.

Thank you
