### ISSUE TITLE
Can't make focuspoint to work

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-responsive-images-plugin#66]
Hello

I wanted to try the focuspoint feature, but can't make it works.

I modified my fields.yaml file to include `focuspoint: true` to my fileupload widget.

I can see the red dot on the image popup, move it, but after saving the focuspoint position, if I reopen the image popup, the red dot return to the center of the image (dont know if it's the normal behavior), on an userpoint feedback, it seems the focuspoint is not saved.

My HTML that display the image is : 

`<img class="lazyload" data-src="{{ image.focus(500, 500, 'crop') }}"  alt="" />`

I can see the image, but it's cropped as regular octobercms crop, with a focus on the center, I can see the custom CSS added by focuspoint, it gives  : 

`<img class="focuspoint-image lazyloaded" data-src="..." sizes="(max-width: 500px) 100vw, 500px" style="width: 100%;height: 100%;object-position: 50% 50%;object-fit: cover" srcset="...">`

The object position is 50%, 50% whereas I put the red dot on the top right corner of the image, so I imagine the origin of the problem is that the focus is not correctly saved.

PS : I use SQLite databse, don't know it it can explain the problem.

Best regards,

**Comment by mtellenbach** [comment]
Hi Zmove

I discovered that the migration of the x- and y-axis values in the system_files will be completely ignored while installing responsiveimages. That's why the values of the "red-dot"-klick will not be stored in the database.

I'll be pushing a new version with this bugfix shortly.

**Comment by mtellenbach** [comment]
This is now fixed in version 2.3.5
