### ISSUE TITLE
Title & description of image not registered when using focuspoint

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-responsive-images-plugin#67]
Hello,

I have a fileupload field that use the focuspoint feature, so I defined focuspoint: true in my fields.yaml file.

It seems that the image title and description are not saved when focuspoint is activated.

To reproduce : 
- Active focuspoint to an upload field
- Upload some images, try to define some title or description to images
- save and reload the page
- Look at the images title and description, they are not saved.

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
Thank you for this bug report. We'll take a look at this problem.

**Comment by tobias-kuendig** [comment]
This should be fixed in v2.3.8. Thank you for the report!
