### ISSUE TITLE
Focuspoint still not working

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-responsive-images-plugin#69]
Hello,

Focuspoint feature still doesn't work as expected despite all recent updates, here is the list of problems I noticed : 

- When you set title and description on image in backend and you save, the image title should be changed to the title you set (core behavior). With focuspoint enabled, the title = the name of the image. (but it's saved correctly with last update)
![Image title](https://user-images.githubusercontent.com/1314678/93564323-c8079f80-f989-11ea-94ac-dfad62872b36.gif)

- The image resize feature doesn't work as expected, here is my html : 
`<img class="image lazyload" data-src="{{ image.focus(500, 500, 'crop') }}" data-sizes="auto" alt="" />`
here is the result : 
![5f18016aabcee320690539__400](https://user-images.githubusercontent.com/1314678/93564571-32204480-f98a-11ea-9f9d-0b5a01f077c8.jpg)
the image is not cropped to be a square.

- The focuspoint css injection does not work at all, with the same html as above + focuspoint options switch set to "on" for both option, here is the html result : 
![html](https://user-images.githubusercontent.com/1314678/93565107-19645e80-f98b-11ea-8497-84fdc890cb57.jpg)

I hope it can help to make it works

Best regards,

**Comment by tobias-kuendig** [comment]
Thank you for this report @Zmove! These issues have been addressed in bae4dfb85d07b90a66b23d66e79af3bb0511a756
