### ISSUE TITLE
Remove height attributes on images

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-responsive-images-plugin#7]
Hello,

I wonder why the plugin add an "height" attribute to the images. It introduce wrong behaviors on the responsive version of the websites.

If you have a fixed height defined, when you resize your browser, the responsive image (width max-width=100%) will adapt it's width, whereas the height stay fixed, so the image will be deformed.

I think the plugin shouldn't define any height to let the CSS do the job.

Is there a good reason to keep the height attribute ?

Alex

**Comment by tobias-kuendig** [comment]
Are you sure the problem is caused by this plugin?

As far as I know, [we don't set the height anywhere](https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/search?q=height&type=Code&utf8=%E2%9C%93)...

**Comment by Alex360hd** [comment]
Oups, yeah it's me. It was my inline editing tool that added height attributes, you plugin just conserve it.
