### ISSUE TITLE
WebP over CDN

### ISSUE THREAD

**Issue by Patesz** [OFFLINE-GmbH/oc-responsive-images-plugin#72]
Hello,
   
Do you know how could I make your plugin work to serve WebP files over CDN server as well?   
I use Speedy plugin (https://octobercms.com/plugin/offline-speedy) to define CDN server.

Thank you,
Patesz

**Comment by tobias-kuendig** [comment]
I don't think that possible. You would have to be able to do redirects on your CDN server and make sure the webp image is pre-generated (you can always do this manually). The plugin looks at the `ACCEPT` http header and checks if it contains `image/webp`, which means, the browser signals support for it. It then does a server side redirect to the webp image, even though the user requested a jpg file. This circumvents the need to change your markup, but you need to be able to run the conversion and redirect on the server, which many CDNs won't allow you to do.

You can always use the `<picture>` element in HTML to server different image formats, but this will require some more manual work.

**Comment by Patesz** [comment]
Thank you for your quick and detailed answer.
It seems it works perfectly with picture tags which means a lot of manual work for me but it works at least. :) 👍
