### ISSUE TITLE
DOM manipulation failed

### ISSUE THREAD

**Issue by rnrkrft** [OFFLINE-GmbH/oc-responsive-images-plugin#73]
[OFFLINE.ResponsiveImages] DOM manipulation failed: DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 1 | 

Any idea, what I miss - log fills up quick
PLESK 18
PHP 7.4
NGINX 1.19

**Comment by tobias-kuendig** [comment]
Do you see any more info in your `system.log` file? It looks like the plugin fails to parse an `<img>` tag in your markup. This could be due to invalid HTML or some other edge-case.

**Comment by rnrkrft** [comment]
Kann es sein, das es an der mod-security scheitert? Die habe ich extra hart eingestellt...

**Comment by tobias-kuendig** [comment]
https://stackoverflow.com/a/14832134 could that be the problem? An unescaped `&` somewhere on the page?

I'll see if we can optimize the logging for these cases.

**Comment by tobias-kuendig** [comment]
Update to 2.3.11, the error should be gone or at least show you the markup of the invalid Tag in the system.log

**Comment by rnrkrft** [comment]
Error is gone!!!!
