### ISSUE TITLE
Add configuration for the srcset attribute

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-responsive-images-plugin#8]
Hello,

I use [this plugin](https://github.com/verlok/lazyload) to manage lazyloading for images, as the famous jQuery lazyload don't support srcset.

However, in order to work, this plugin need the 'data-original-set' attribute defined (in place of srcset).

You already defined an option in the config file to define an alternate src attribute to make it compatible with plugins for lazyloading. I think you should add another option in the config file, the attribute you want to define for the srcset.

It should not be a big deal

Alex

**Comment by tobias-kuendig** [comment]
This feature was implemented in version 1.1.0. Thanks for your input!
