### ISSUE TITLE
.htaccess for webp on Apache 2.2

### ISSUE THREAD

**Issue by RobertCh2** [OFFLINE-GmbH/oc-responsive-images-plugin#80]
What should be working .htaccess configuration on Apache 2.2, as END flag is working on Apache 2.3?

**Comment by tobias-kuendig** [comment]
The Apache config is more of an example and meant as an easy option for most of the plugin users that are on Apache 2.3. We do not officially support older versions, but you should be able to get the config working anyways.

For a start, you can try and replace the `END` flags with the `L` flag. While not completely the same, they both suppress the processing of other rules. As long as you don't have any other .htaccess files in other subdirectories, the `L` should work as well.

Please post your config here if you get it working with Apache 2.2.

Related #53
