### ISSUE TITLE
Wrong thumbs being generated

### ISSUE THREAD

**Issue by SebastiaanKloos** [OFFLINE-GmbH/oc-responsive-images-plugin#81]
After I've moved the website to another server, the wrong thumbs are being generated. Take this image for example.

Original image:
https://www.koningbordspel.nl/storage/app/uploads/public/5f2/589/0f1/5f25890f1169a999353708.jpeg

Thumb being generated:
https://www.koningbordspel.nl/storage/app/uploads/public/5f2/589/0f1/thumb__400_400_0_0_auto.jpeg

It's because there are more than one image in the `0f1` directory.  So wouldn't it be better to include the filename in the thumbs being generated?

**Comment by tobias-kuendig** [comment]
Hm, that's strange. I have never experienced this problem myself.

We do actually use the filename to generate the directories: https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/14ad48e19af0390207b568a0ac3c8f919bc928b6/classes/ResponsiveImage.php#L261

Maybe there is a collision?

Looking at your path, the files are stored in the storage/app/uploads/public directory, we do however store everything in the storage/temp directory: https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/14ad48e19af0390207b568a0ac3c8f919bc928b6/classes/ResponsiveImage.php#L228

I wonder if the links you posted are actually generated by this plugin, or if these are the default October thumbnails?

**Comment by SebastiaanKloos** [comment]
@tobias-kuendig I'm so sorry. You're completely right. I'm using the October CMS thumbnails there. Thanks for your time!
