### ISSUE TITLE
ImageResizer doesn't work anymore with OctoberCMS after release 2.4.4 (Optimized compatibility with WinterCMS)

### ISSUE THREAD

**Issue by lemariva** [OFFLINE-GmbH/oc-responsive-images-plugin#87]
The PR #85 only works with WinterCMS because the function `class_exists('ResizerOC')` always returns `false`. This is explained [here](https://www.php.net/manual/de/function.class-exists.php#113581)  (the comment is old but PHP7.4 still works like that). The function `class_exists` doesn't work with the short alias of a namespaced class. A quick fix for the file would be to change the line: https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/51eefbf52d4c87d960b52491c8706cd321259bda/classes/ImageResizer.php#L8 to:
```php
if (class_exists('October\Rain\Resize\Resizer')) {
```
I think sending a PR for that change is too much (and I'm not sure if it works with WinterCMS). Maybe @matteotrubini can check if that works, commit & push the change, and pull another request. Grazie! :)

**Comment by tobias-kuendig** [comment]
Thank you for the heads-up @lemariva! I have reverted the PR and released a new version. As I do not need Winter CMS someone else needs to come up with a working solution. For the time being the compatibility fix for Winter CMS has been removed again.

**Comment by lemariva** [comment]
Thanks for the promptly answer and update. I saw and installed the latest version. It seems to work again. I close the issue then.

**Comment by matteotrubini** [comment]
@lemariva thankyou, there is always something to learn :wink:
